version: '3'

volumes:
  gems:
    driver: ${VOLUMES_DRIVER}
  node_modules:
    driver: ${VOLUMES_DRIVER}
  postgres:
    driver: ${VOLUMES_DRIVER}
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
  memcached:
    driver: ${VOLUMES_DRIVER}

services:

  rails:
    build:
      context: ./ruby
      args:
        - RAILSDOCK_RUBY_VERSION=${RUBY_VERSION}
        - RAILSDOCK_BUNDLE_JOBS=${BUNDLE_JOBS}
        - RAILSDOCK_BUNDLE_RETRY=${BUNDLE_RETRY}
        - RAILSDOCK_NODE_VERSION=${NODE_VERSION}
        - INSTALL_PG_CLIENT=${INSTALL_PG_CLIENT}
        - UID=${RUBY_UID}
        - GID=${RUBY_GID}
    environment:
      - DATABASE_ADAPTER=${DATABASE_ADAPTER}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - gems:/gems
      - node_modules:${APP_CODE_PATH_CONTAINER}/node_modules
    ports:
      - "${RAILS_SERVER_HOST_PORT}:3000"
    user: ruby
    tty: true
    stdin_open: true
    depends_on:
      - postgres

  postgres:
    build:
      context: ./postgres
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - mysql:/var/lib/mysql

  redis:
    build:
      context: ./redis
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - redis:/data

  memcached:
    build:
      context: ./memcached
      args:
        - MEMCACHED_VERSION=${MEMCACHED_VERSION}
    ports:
      - "${MEMCACHED_HOST_PORT}:11211"
    volumes:
      - memcached:/var/lib/memcached
