version: '3'

volumes:
  gems:
    driver: ${VOLUMES_DRIVER}
  postgres:
    driver: ${VOLUMES_DRIVER}

services:

  ruby:
    build:
      context: ./ruby
      args:
        - RAILSDOCK_RUBY_VERSION=${RUBY_VERSION}
        - RAILSDOCK_BUNDLE_JOBS=${BUNDLE_JOBS}
        - RAILSDOCK_BUNDLE_RETRY=${BUNDLE_RETRY}
        - INSTALL_PG_CLIENT=${INSTALL_PG_CLIENT}
      environment:
        - DATABASE_ADAPTER=${DATABASE_ADAPTER}
        - DATABASE_USER=${DATABASE_USER}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_HOST=${DATABASE_HOST}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - gems:/gems
    ports:
      - "${RAILS_SERVER_PORT}:3000"
    tty: true
    stdin_open: true
    depends_on:
      - postgres

  postgres:
    build: ./postgres
    args:
      - POSTGRES_VERSION=${POSTGRES_VERSION}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
